#' A wraper to indiedown::pdf_document_with_asset() that will be auto generated by a helper function in indiedown
#'
#' @export
#' @importFrom indiedown pdf_document_with_asset
zurichdown <- function(...) {
  indiedown::pdf_document_with_asset(
    path = system.file("indiedown", package = getPackageName()),
    highlight = "pygments",
    latex_engine = "lualatex",
    ...
  )
}
