name: "Action to deploy a pkgdown website"

runs:
  using: "composite"
  steps:
    - name: Deploy site
      uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2
      with:
        timeout_minutes: 15
        max_attempts: 10
        command: |
          R -q -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
