name: 'Action to deploy a pkgdown website'

runs:
  using: "composite"
  steps:
    - name: "Band aid: install rmarkdown from GitHub in older R"
      run: |
        if (getRversion() < "3.5" && packageVersion("rmarkdown") < "2.13") {
          pak::pak("rstudio/rmarkdown")
        }
      shell: Rscript {0}

    - name: Deploy site
      run: |
        pkgdown::deploy_to_branch(new_process = FALSE)
      shell: Rscript {0}
