name: 'Action to build a pkgdown website'

runs:
  using: "composite"
  steps:
    - name: "Band aid: install rmarkdown from GitHub in older R"
      run: |
        if (getRversion() < "3.5" && packageVersion("rmarkdown") < "2.13") {
          pak::pak("rstudio/rmarkdown")
        }
      shell: Rscript {0}

    - name: Build site
      run: |
        pkgdown::build_site()
      shell: Rscript {0}
